### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by eghbal** [pacoesteban/Rarbg-torrentapi#2]
Hello,

torrentapi.org website is currently down so the API doesn't work anymore.

**Comment by pacoesteban** [comment]
Not sure what you mean ... torrentapi.org works fine. And the Perl module too.

Check here: https://torrentapi.org/apidocs_v2.txt

And you can also check it simply like this:

```
#!/usr/bin/env perl

use Rarbg::torrentapi;
use Data::Dumper;
use v5.24;

my $tapi = Rarbg::torrentapi->new();
my $search = $tapi->search({
    search_imdb => 'tt1375666'
});

say Dumper($search);
```
