### ISSUE TITLE
Cannot get token 429 Too Many Requests at /usr/local/share/perl/5.22.1/Rarbg/torrentapi.pm line 95.

### ISSUE THREAD

**Issue by nrk666** [pacoesteban/Rarbg-torrentapi#4]
Constantly getting this error after updating to 0.16: 

"Cannot get token 429 Too Many Requests at /usr/local/share/perl/5.22.1/Rarbg/torrentapi.pm line 95."

I've yet to retrieve any results at all.

**Comment by pacoesteban** [comment]
Torrentapi time limit on requests was making the module crash.
I've implemented a nasty solution ... The token renewal sleeps 1 second, so you can make requests after that.

Is up to you to enforce the 1rqs/2s policy of torrentapi afterwards (check https://torrentapi.org/apidocs_v2.txt).

Changes are commited to v0.1.7.
It's already available here and will be soon on CPAN.

**Comment by nrk666** [comment]
Confirmed this is now working again. I was doing one search every 60 minutes which is why it was confusing to get that error. Thanks for the quick response on this.
